/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_ActiveTimeMethod_H_
#define	_ActiveTimeMethod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ActiveTimeMethod {
	ActiveTimeMethod_duration	= 1,
	ActiveTimeMethod_inactivityIncluded	= 2,
	ActiveTimeMethod_inactivity	= 3,
	ActiveTimeMethod_activePeriods	= 4
} e_ActiveTimeMethod;

/* ActiveTimeMethod */
typedef long	 ActiveTimeMethod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActiveTimeMethod;
asn_struct_free_f ActiveTimeMethod_free;
asn_struct_print_f ActiveTimeMethod_print;
asn_constr_check_f ActiveTimeMethod_constraint;
ber_type_decoder_f ActiveTimeMethod_decode_ber;
der_type_encoder_f ActiveTimeMethod_encode_der;
xer_type_decoder_f ActiveTimeMethod_decode_xer;
xer_type_encoder_f ActiveTimeMethod_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ActiveTimeMethod_H_ */
#include <asn_internal.h>
