/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_AFChargingIdentifier_H_
#define	_AFChargingIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AFChargingIdentifier */
typedef OCTET_STRING_t	 AFChargingIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AFChargingIdentifier;
asn_struct_free_f AFChargingIdentifier_free;
asn_struct_print_f AFChargingIdentifier_print;
asn_constr_check_f AFChargingIdentifier_constraint;
ber_type_decoder_f AFChargingIdentifier_decode_ber;
der_type_encoder_f AFChargingIdentifier_encode_der;
xer_type_decoder_f AFChargingIdentifier_decode_xer;
xer_type_encoder_f AFChargingIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AFChargingIdentifier_H_ */
#include <asn_internal.h>
