/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#include "ChangeOfServiceCondition.h"

static asn_TYPE_member_t asn_MBR_aFRecordInformation_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AFRecordInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_aFRecordInformation_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_aFRecordInformation_specs_17 = {
	sizeof(struct aFRecordInformation),
	offsetof(struct aFRecordInformation, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_aFRecordInformation_17 = {
	"aFRecordInformation",
	"aFRecordInformation",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_aFRecordInformation_tags_17,
	sizeof(asn_DEF_aFRecordInformation_tags_17)
		/sizeof(asn_DEF_aFRecordInformation_tags_17[0]) - 1, /* 1 */
	asn_DEF_aFRecordInformation_tags_17,	/* Same as above */
	sizeof(asn_DEF_aFRecordInformation_tags_17)
		/sizeof(asn_DEF_aFRecordInformation_tags_17[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_aFRecordInformation_17,
	1,	/* Single element */
	&asn_SPC_aFRecordInformation_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ChangeOfServiceCondition_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfServiceCondition, ratingGroup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RatingGroupId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ratingGroup"
		},
	{ ATF_POINTER, 5, offsetof(struct ChangeOfServiceCondition, resultCode),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ResultCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resultCode"
		},
	{ ATF_POINTER, 4, offsetof(struct ChangeOfServiceCondition, localSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localSequenceNumber"
		},
	{ ATF_POINTER, 3, offsetof(struct ChangeOfServiceCondition, timeOfFirstUsage),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeOfFirstUsage"
		},
	{ ATF_POINTER, 2, offsetof(struct ChangeOfServiceCondition, timeOfLastUsage),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeOfLastUsage"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfServiceCondition, timeUsage),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallDuration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeUsage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfServiceCondition, serviceConditionChange),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceConditionChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceConditionChange"
		},
	{ ATF_POINTER, 4, offsetof(struct ChangeOfServiceCondition, qoSInformationNeg),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EPCQoSInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qoSInformationNeg"
		},
	{ ATF_POINTER, 3, offsetof(struct ChangeOfServiceCondition, servingNodeAddress),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GSNAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingNodeAddress"
		},
	{ ATF_POINTER, 2, offsetof(struct ChangeOfServiceCondition, datavolumeFBCUplink),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataVolumeGPRS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"datavolumeFBCUplink"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfServiceCondition, datavolumeFBCDownlink),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataVolumeGPRS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"datavolumeFBCDownlink"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfServiceCondition, timeOfReport),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeOfReport"
		},
	{ ATF_POINTER, 3, offsetof(struct ChangeOfServiceCondition, failureHandlingContinue),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FailureHandlingContinue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"failureHandlingContinue"
		},
	{ ATF_POINTER, 2, offsetof(struct ChangeOfServiceCondition, serviceIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceIdentifier"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfServiceCondition, pSFurnishChargingInformation),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PSFurnishChargingInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pSFurnishChargingInformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfServiceCondition, aFRecordInformation),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		0,
		&asn_DEF_aFRecordInformation_17,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aFRecordInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfServiceCondition, userLocationInformation),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userLocationInformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChangeOfServiceCondition, eventBasedChargingInformation),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventBasedChargingInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventBasedChargingInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct ChangeOfServiceCondition, threeGPP2UserLocationInformation),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"threeGPP2UserLocationInformation"
		},
};
static const ber_tlv_tag_t asn_DEF_ChangeOfServiceCondition_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ChangeOfServiceCondition_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* ratingGroup */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* resultCode */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 }, /* localSequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 3, 0, 0 }, /* timeOfFirstUsage */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 4, 0, 0 }, /* timeOfLastUsage */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 5, 0, 0 }, /* timeUsage */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 6, 0, 0 }, /* serviceConditionChange */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* qoSInformationNeg */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* servingNodeAddress */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* datavolumeFBCUplink */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 10, 0, 0 }, /* datavolumeFBCDownlink */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 11, 0, 0 }, /* timeOfReport */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 12, 0, 0 }, /* failureHandlingContinue */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 13, 0, 0 }, /* serviceIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 14, 0, 0 }, /* pSFurnishChargingInformation */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 15, 0, 0 }, /* aFRecordInformation */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 16, 0, 0 }, /* userLocationInformation */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 17, 0, 0 }, /* eventBasedChargingInformation */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 18, 0, 0 } /* threeGPP2UserLocationInformation */
};
static asn_SEQUENCE_specifics_t asn_SPC_ChangeOfServiceCondition_specs_1 = {
	sizeof(struct ChangeOfServiceCondition),
	offsetof(struct ChangeOfServiceCondition, _asn_ctx),
	asn_MAP_ChangeOfServiceCondition_tag2el_1,
	19,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ChangeOfServiceCondition = {
	"ChangeOfServiceCondition",
	"ChangeOfServiceCondition",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ChangeOfServiceCondition_tags_1,
	sizeof(asn_DEF_ChangeOfServiceCondition_tags_1)
		/sizeof(asn_DEF_ChangeOfServiceCondition_tags_1[0]), /* 1 */
	asn_DEF_ChangeOfServiceCondition_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChangeOfServiceCondition_tags_1)
		/sizeof(asn_DEF_ChangeOfServiceCondition_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ChangeOfServiceCondition_1,
	19,	/* Elements count */
	&asn_SPC_ChangeOfServiceCondition_specs_1	/* Additional specs */
};

