/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#include "CreditControlInfo.h"

static int
memb_creditControlSessionId_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ccsRealm_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_CreditControlInfo_1[] = {
	{ ATF_POINTER, 3, offsetof(struct CreditControlInfo, creditControlFailureReport),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CreditControlFailureReport,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"creditControlFailureReport"
		},
	{ ATF_POINTER, 2, offsetof(struct CreditControlInfo, creditControlSessionId),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_creditControlSessionId_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"creditControlSessionId"
		},
	{ ATF_POINTER, 1, offsetof(struct CreditControlInfo, ccsRealm),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_ccsRealm_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ccsRealm"
		},
};
static const ber_tlv_tag_t asn_DEF_CreditControlInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CreditControlInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 }, /* creditControlFailureReport */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 1, 0, 0 }, /* creditControlSessionId */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 2, 0, 0 } /* ccsRealm */
};
static asn_SEQUENCE_specifics_t asn_SPC_CreditControlInfo_specs_1 = {
	sizeof(struct CreditControlInfo),
	offsetof(struct CreditControlInfo, _asn_ctx),
	asn_MAP_CreditControlInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CreditControlInfo = {
	"CreditControlInfo",
	"CreditControlInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CreditControlInfo_tags_1,
	sizeof(asn_DEF_CreditControlInfo_tags_1)
		/sizeof(asn_DEF_CreditControlInfo_tags_1[0]), /* 1 */
	asn_DEF_CreditControlInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_CreditControlInfo_tags_1)
		/sizeof(asn_DEF_CreditControlInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CreditControlInfo_1,
	3,	/* Elements count */
	&asn_SPC_CreditControlInfo_specs_1	/* Additional specs */
};

