/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_CreditControlInfo_H_
#define	_CreditControlInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CreditControlFailureReport;

/* CreditControlInfo */
typedef struct CreditControlInfo {
	struct CreditControlFailureReport	*creditControlFailureReport	/* OPTIONAL */;
	OCTET_STRING_t	*creditControlSessionId	/* OPTIONAL */;
	OCTET_STRING_t	*ccsRealm	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreditControlInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreditControlInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CreditControlFailureReport.h"

#endif	/* _CreditControlInfo_H_ */
#include <asn_internal.h>
