/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_GprsCdrExtensions_H_
#define	_GprsCdrExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum GprsCdrExtensions_PR {
	GprsCdrExtensions_PR_creditControlInfo,	/* Member creditControlInfo is present */
	GprsCdrExtensions_PR_policyControlInfo,	/* Member policyControlInfo is present */
	GprsCdrExtensions_PR_userCategory,	/* Member userCategory is present */
	GprsCdrExtensions_PR_ruleSpaceId,	/* Member ruleSpaceId is present */
	GprsCdrExtensions_PR_serviceContainers,	/* Member serviceContainers is present */
	GprsCdrExtensions_PR_timeReports,	/* Member timeReports is present */
	GprsCdrExtensions_PR_dataZoneInfo,	/* Member dataZoneInfo is present */
	GprsCdrExtensions_PR_creditStatus,	/* Member creditStatus is present */
} GprsCdrExtensions_PR;

/* Forward declarations */
struct CreditControlInfo;
struct PolicyControlInfo;
struct ServiceContainer;
struct TimeReport;

/* GprsCdrExtensions */
typedef struct GprsCdrExtensions {
	struct CreditControlInfo	*creditControlInfo	/* OPTIONAL */;
	struct PolicyControlInfo	*policyControlInfo	/* OPTIONAL */;
	long	*userCategory	/* OPTIONAL */;
	IA5String_t	*ruleSpaceId	/* OPTIONAL */;
	struct serviceContainers {
		A_SEQUENCE_OF(struct ServiceContainer) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *serviceContainers;
	struct timeReports {
		A_SEQUENCE_OF(struct TimeReport) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *timeReports;
	IA5String_t	*dataZoneInfo	/* OPTIONAL */;
	long	*creditStatus	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pGprsCdrExtensions, GprsCdrExtensions_PR_x) */
	unsigned int _presence_map
		[((8+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GprsCdrExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GprsCdrExtensions;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CreditControlInfo.h"
#include "PolicyControlInfo.h"
#include "ServiceContainer.h"
#include "TimeReport.h"

#endif	/* _GprsCdrExtensions_H_ */
#include <asn_internal.h>
