/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_IPAddress_H_
#define	_IPAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IPBinaryAddress.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IPAddress */
typedef IPBinaryAddress_t	 IPAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPAddress;
asn_struct_free_f IPAddress_free;
asn_struct_print_f IPAddress_print;
asn_constr_check_f IPAddress_constraint;
ber_type_decoder_f IPAddress_decode_ber;
der_type_encoder_f IPAddress_encode_der;
xer_type_decoder_f IPAddress_decode_xer;
xer_type_encoder_f IPAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IPAddress_H_ */
#include <asn_internal.h>
