/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#include "IPFlow.h"

static asn_TYPE_member_t asn_MBR_listOfURIIPFlow_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfURIIPFlow_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfURIIPFlow_specs_9 = {
	sizeof(struct listOfURIIPFlow),
	offsetof(struct listOfURIIPFlow, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfURIIPFlow_9 = {
	"listOfURIIPFlow",
	"listOfURIIPFlow",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfURIIPFlow_tags_9,
	sizeof(asn_DEF_listOfURIIPFlow_tags_9)
		/sizeof(asn_DEF_listOfURIIPFlow_tags_9[0]) - 1, /* 1 */
	asn_DEF_listOfURIIPFlow_tags_9,	/* Same as above */
	sizeof(asn_DEF_listOfURIIPFlow_tags_9)
		/sizeof(asn_DEF_listOfURIIPFlow_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfURIIPFlow_9,
	1,	/* Single element */
	&asn_SPC_listOfURIIPFlow_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IPFlow_1[] = {
	{ ATF_POINTER, 8, offsetof(struct IPFlow, uEAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IPAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"uEAddress"
		},
	{ ATF_POINTER, 7, offsetof(struct IPFlow, uEPort),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPPort,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"uEPort"
		},
	{ ATF_POINTER, 6, offsetof(struct IPFlow, networkAddress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IPAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkAddress"
		},
	{ ATF_POINTER, 5, offsetof(struct IPFlow, networkPort),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPPort,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkPort"
		},
	{ ATF_POINTER, 4, offsetof(struct IPFlow, protocol),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPProtocol,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocol"
		},
	{ ATF_POINTER, 3, offsetof(struct IPFlow, dataVolumeUplink),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeUplink"
		},
	{ ATF_POINTER, 2, offsetof(struct IPFlow, dataVolumeDownlink),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeDownlink"
		},
	{ ATF_POINTER, 1, offsetof(struct IPFlow, listOfURIIPFlow),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_listOfURIIPFlow_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfURIIPFlow"
		},
};
static const ber_tlv_tag_t asn_DEF_IPFlow_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IPFlow_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* uEAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* uEPort */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* networkAddress */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* networkPort */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* protocol */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* dataVolumeUplink */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* dataVolumeDownlink */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 } /* listOfURIIPFlow */
};
static asn_SEQUENCE_specifics_t asn_SPC_IPFlow_specs_1 = {
	sizeof(struct IPFlow),
	offsetof(struct IPFlow, _asn_ctx),
	asn_MAP_IPFlow_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IPFlow = {
	"IPFlow",
	"IPFlow",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IPFlow_tags_1,
	sizeof(asn_DEF_IPFlow_tags_1)
		/sizeof(asn_DEF_IPFlow_tags_1[0]), /* 1 */
	asn_DEF_IPFlow_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPFlow_tags_1)
		/sizeof(asn_DEF_IPFlow_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IPFlow_1,
	8,	/* Elements count */
	&asn_SPC_IPFlow_specs_1	/* Additional specs */
};

