/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_IPPort_H_
#define	_IPPort_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IPPort */
typedef long	 IPPort_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPPort;
asn_struct_free_f IPPort_free;
asn_struct_print_f IPPort_print;
asn_constr_check_f IPPort_constraint;
ber_type_decoder_f IPPort_decode_ber;
der_type_encoder_f IPPort_encode_der;
xer_type_decoder_f IPPort_decode_xer;
xer_type_encoder_f IPPort_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IPPort_H_ */
#include <asn_internal.h>
