/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_IPProtocol_H_
#define	_IPProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IPProtocol */
typedef long	 IPProtocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPProtocol;
asn_struct_free_f IPProtocol_free;
asn_struct_print_f IPProtocol_print;
asn_constr_check_f IPProtocol_constraint;
ber_type_decoder_f IPProtocol_decode_ber;
der_type_encoder_f IPProtocol_encode_der;
xer_type_decoder_f IPProtocol_decode_xer;
xer_type_encoder_f IPProtocol_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IPProtocol_H_ */
#include <asn_internal.h>
