/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_MSTimeZone_H_
#define	_MSTimeZone_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MSTimeZone */
typedef OCTET_STRING_t	 MSTimeZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MSTimeZone;
asn_struct_free_f MSTimeZone_free;
asn_struct_print_f MSTimeZone_print;
asn_constr_check_f MSTimeZone_constraint;
ber_type_decoder_f MSTimeZone_decode_ber;
der_type_encoder_f MSTimeZone_encode_der;
xer_type_decoder_f MSTimeZone_decode_xer;
xer_type_encoder_f MSTimeZone_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MSTimeZone_H_ */
#include <asn_internal.h>
