/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_PolicyControlFailureReport_H_
#define	_PolicyControlFailureReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PolicyRequestType.h"
#include "PolicyRequestStatus.h"
#include "PolicyResultCode.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PolicyControlFailureReport */
typedef struct PolicyControlFailureReport {
	PolicyRequestType_t	 requestType;
	PolicyRequestStatus_t	 requestStatus;
	PolicyResultCode_t	*resultCode	/* OPTIONAL */;
	TimeStamp_t	*stopTime	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PolicyControlFailureReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyControlFailureReport;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyControlFailureReport_H_ */
#include <asn_internal.h>
