/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_PolicyRequestStatus_H_
#define	_PolicyRequestStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PolicyRequestStatus {
	PolicyRequestStatus_unsent	= 0,
	PolicyRequestStatus_noAnswer	= 1,
	PolicyRequestStatus_failure	= 2,
	PolicyRequestStatus_pCRFRestart	= 3
} e_PolicyRequestStatus;

/* PolicyRequestStatus */
typedef long	 PolicyRequestStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyRequestStatus;
asn_struct_free_f PolicyRequestStatus_free;
asn_struct_print_f PolicyRequestStatus_print;
asn_constr_check_f PolicyRequestStatus_constraint;
ber_type_decoder_f PolicyRequestStatus_decode_ber;
der_type_encoder_f PolicyRequestStatus_encode_der;
xer_type_decoder_f PolicyRequestStatus_decode_xer;
xer_type_encoder_f PolicyRequestStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyRequestStatus_H_ */
#include <asn_internal.h>
