/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_PolicyRequestType_H_
#define	_PolicyRequestType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PolicyRequestType {
	PolicyRequestType_start	= 0,
	PolicyRequestType_interim	= 1,
	PolicyRequestType_stop	= 2
} e_PolicyRequestType;

/* PolicyRequestType */
typedef long	 PolicyRequestType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyRequestType;
asn_struct_free_f PolicyRequestType_free;
asn_struct_print_f PolicyRequestType_print;
asn_constr_check_f PolicyRequestType_constraint;
ber_type_decoder_f PolicyRequestType_decode_ber;
der_type_encoder_f PolicyRequestType_encode_der;
xer_type_decoder_f PolicyRequestType_decode_xer;
xer_type_encoder_f PolicyRequestType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyRequestType_H_ */
#include <asn_internal.h>
