/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_PolicyResultCode_H_
#define	_PolicyResultCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PolicyResultCode */
typedef long	 PolicyResultCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyResultCode;
asn_struct_free_f PolicyResultCode_free;
asn_struct_print_f PolicyResultCode_print;
asn_constr_check_f PolicyResultCode_constraint;
ber_type_decoder_f PolicyResultCode_decode_ber;
der_type_encoder_f PolicyResultCode_encode_der;
xer_type_decoder_f PolicyResultCode_decode_xer;
xer_type_encoder_f PolicyResultCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyResultCode_H_ */
#include <asn_internal.h>
