/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_PolicyControlInfo_H_
#define	_PolicyControlInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PolicyControlFailureReport;

/* PolicyControlInfo */
typedef struct PolicyControlInfo {
	struct PolicyControlFailureReport	*policyControlFailureReport	/* OPTIONAL */;
	OCTET_STRING_t	*pcsRealm	/* OPTIONAL */;
	OCTET_STRING_t	*policyControlSessionId	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PolicyControlInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyControlInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PolicyControlFailureReport.h"

#endif	/* _PolicyControlInfo_H_ */
#include <asn_internal.h>
