/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#include "PolicyControlFailureReport.h"

static asn_TYPE_member_t asn_MBR_PolicyControlFailureReport_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyControlFailureReport, requestType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PolicyRequestType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyControlFailureReport, requestStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PolicyRequestStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestStatus"
		},
	{ ATF_POINTER, 2, offsetof(struct PolicyControlFailureReport, resultCode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PolicyResultCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resultCode"
		},
	{ ATF_POINTER, 1, offsetof(struct PolicyControlFailureReport, stopTime),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stopTime"
		},
};
static const ber_tlv_tag_t asn_DEF_PolicyControlFailureReport_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PolicyControlFailureReport_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* requestType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* requestStatus */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* resultCode */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 3, 0, 0 } /* stopTime */
};
static asn_SEQUENCE_specifics_t asn_SPC_PolicyControlFailureReport_specs_1 = {
	sizeof(struct PolicyControlFailureReport),
	offsetof(struct PolicyControlFailureReport, _asn_ctx),
	asn_MAP_PolicyControlFailureReport_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PolicyControlFailureReport = {
	"PolicyControlFailureReport",
	"PolicyControlFailureReport",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PolicyControlFailureReport_tags_1,
	sizeof(asn_DEF_PolicyControlFailureReport_tags_1)
		/sizeof(asn_DEF_PolicyControlFailureReport_tags_1[0]), /* 1 */
	asn_DEF_PolicyControlFailureReport_tags_1,	/* Same as above */
	sizeof(asn_DEF_PolicyControlFailureReport_tags_1)
		/sizeof(asn_DEF_PolicyControlFailureReport_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PolicyControlFailureReport_1,
	4,	/* Elements count */
	&asn_SPC_PolicyControlFailureReport_specs_1	/* Additional specs */
};

