/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_RatingGroup_H_
#define	_RatingGroup_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RatingGroup */
typedef long	 RatingGroup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RatingGroup;
asn_struct_free_f RatingGroup_free;
asn_struct_print_f RatingGroup_print;
asn_constr_check_f RatingGroup_constraint;
ber_type_decoder_f RatingGroup_decode_ber;
der_type_encoder_f RatingGroup_encode_der;
xer_type_decoder_f RatingGroup_decode_xer;
xer_type_encoder_f RatingGroup_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RatingGroup_H_ */
#include <asn_internal.h>
