/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_RATType_H_
#define	_RATType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RATType */
typedef long	 RATType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RATType;
asn_struct_free_f RATType_free;
asn_struct_print_f RATType_print;
asn_constr_check_f RATType_constraint;
ber_type_decoder_f RATType_decode_ber;
der_type_encoder_f RATType_encode_der;
xer_type_decoder_f RATType_decode_xer;
xer_type_encoder_f RATType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RATType_H_ */
#include <asn_internal.h>
