/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#include "ServiceContainer.h"

static asn_TYPE_member_t asn_MBR_listOfURI_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_URI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfURI_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfURI_specs_10 = {
	sizeof(struct listOfURI),
	offsetof(struct listOfURI, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfURI_10 = {
	"listOfURI",
	"listOfURI",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfURI_tags_10,
	sizeof(asn_DEF_listOfURI_tags_10)
		/sizeof(asn_DEF_listOfURI_tags_10[0]) - 1, /* 1 */
	asn_DEF_listOfURI_tags_10,	/* Same as above */
	sizeof(asn_DEF_listOfURI_tags_10)
		/sizeof(asn_DEF_listOfURI_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfURI_10,
	1,	/* Single element */
	&asn_SPC_listOfURI_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listOfIPFlow_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IPFlow,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfIPFlow_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfIPFlow_specs_12 = {
	sizeof(struct listOfIPFlow),
	offsetof(struct listOfIPFlow, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfIPFlow_12 = {
	"listOfIPFlow",
	"listOfIPFlow",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfIPFlow_tags_12,
	sizeof(asn_DEF_listOfIPFlow_tags_12)
		/sizeof(asn_DEF_listOfIPFlow_tags_12[0]) - 1, /* 1 */
	asn_DEF_listOfIPFlow_tags_12,	/* Same as above */
	sizeof(asn_DEF_listOfIPFlow_tags_12)
		/sizeof(asn_DEF_listOfIPFlow_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfIPFlow_12,
	1,	/* Single element */
	&asn_SPC_listOfIPFlow_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ServiceContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceContainer, ratingGroup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RatingGroup,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ratingGroup"
		},
	{ ATF_POINTER, 9, offsetof(struct ServiceContainer, serviceIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceIdentifier"
		},
	{ ATF_POINTER, 8, offsetof(struct ServiceContainer, localSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localSequenceNumber"
		},
	{ ATF_POINTER, 7, offsetof(struct ServiceContainer, method),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActiveTimeMethod,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"method"
		},
	{ ATF_POINTER, 6, offsetof(struct ServiceContainer, inactivity),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"inactivity"
		},
	{ ATF_POINTER, 5, offsetof(struct ServiceContainer, resolution),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resolution"
		},
	{ ATF_POINTER, 4, offsetof(struct ServiceContainer, ccRequestNumber),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ccRequestNumber"
		},
	{ ATF_POINTER, 3, offsetof(struct ServiceContainer, serviceSpecificUnits),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceSpecificUnits"
		},
	{ ATF_POINTER, 2, offsetof(struct ServiceContainer, listOfURI),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		0,
		&asn_DEF_listOfURI_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfURI"
		},
	{ ATF_POINTER, 1, offsetof(struct ServiceContainer, listOfIPFlow),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_listOfIPFlow_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfIPFlow"
		},
};
static const ber_tlv_tag_t asn_DEF_ServiceContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ServiceContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* ratingGroup */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* serviceIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* localSequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* method */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* inactivity */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* resolution */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* ccRequestNumber */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* serviceSpecificUnits */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* listOfURI */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 9, 0, 0 } /* listOfIPFlow */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServiceContainer_specs_1 = {
	sizeof(struct ServiceContainer),
	offsetof(struct ServiceContainer, _asn_ctx),
	asn_MAP_ServiceContainer_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServiceContainer = {
	"ServiceContainer",
	"ServiceContainer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServiceContainer_tags_1,
	sizeof(asn_DEF_ServiceContainer_tags_1)
		/sizeof(asn_DEF_ServiceContainer_tags_1[0]), /* 1 */
	asn_DEF_ServiceContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceContainer_tags_1)
		/sizeof(asn_DEF_ServiceContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ServiceContainer_1,
	10,	/* Elements count */
	&asn_SPC_ServiceContainer_specs_1	/* Additional specs */
};

