/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_ServingNodeType_H_
#define	_ServingNodeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingNodeType {
	ServingNodeType_sGSN	= 0,
	ServingNodeType_pMIPSGW	= 1,
	ServingNodeType_gTPSGW	= 2,
	ServingNodeType_ePDG	= 3,
	ServingNodeType_hSGW	= 4,
	ServingNodeType_mME	= 5
} e_ServingNodeType;

/* ServingNodeType */
typedef long	 ServingNodeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingNodeType;
asn_struct_free_f ServingNodeType_free;
asn_struct_print_f ServingNodeType_print;
asn_constr_check_f ServingNodeType_constraint;
ber_type_decoder_f ServingNodeType_decode_ber;
der_type_encoder_f ServingNodeType_encode_der;
xer_type_decoder_f ServingNodeType_decode_xer;
xer_type_encoder_f ServingNodeType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServingNodeType_H_ */
#include <asn_internal.h>
