/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_ServiceConditionChange_H_
#define	_ServiceConditionChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceConditionChange {
	ServiceConditionChange_qoSChange	= 0,
	ServiceConditionChange_sGSNChange	= 1,
	ServiceConditionChange_sGSNPLMNIDChange	= 2,
	ServiceConditionChange_tariffTimeSwitch	= 3,
	ServiceConditionChange_pDPContextRelease	= 4,
	ServiceConditionChange_rATChange	= 5,
	ServiceConditionChange_configurationChange	= 8,
	ServiceConditionChange_serviceStop	= 9,
	ServiceConditionChange_dCCATimeThresholdReached	= 10,
	ServiceConditionChange_dCCAVolumeThresholdReached	= 11,
	ServiceConditionChange_dCCAServiceSpecificUnitThresholdReached	= 12,
	ServiceConditionChange_dCCATimeExhausted	= 13,
	ServiceConditionChange_dCCAVolumeExhausted	= 14,
	ServiceConditionChange_dCCAValidityTimeout	= 15,
	ServiceConditionChange_dCCAReauthorisationRequest	= 17,
	ServiceConditionChange_dCCAContinueOngoingSession	= 18,
	ServiceConditionChange_dCCARetryAndTerminateOngoingSession	= 19,
	ServiceConditionChange_dCCATerminateOngoingSession	= 20,
	ServiceConditionChange_cGI_SAIChange	= 21,
	ServiceConditionChange_rAIChange	= 22,
	ServiceConditionChange_dCCAServiceSpecificUnitExhausted	= 23,
	ServiceConditionChange_recordClosure	= 24,
	ServiceConditionChange_eCGIChange	= 29,
	ServiceConditionChange_tAIChange	= 30
} e_ServiceConditionChange;

/* ServiceConditionChange */
typedef BIT_STRING_t	 ServiceConditionChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceConditionChange;
asn_struct_free_f ServiceConditionChange_free;
asn_struct_print_f ServiceConditionChange_print;
asn_constr_check_f ServiceConditionChange_constraint;
ber_type_decoder_f ServiceConditionChange_decode_ber;
der_type_encoder_f ServiceConditionChange_encode_der;
xer_type_decoder_f ServiceConditionChange_decode_xer;
xer_type_encoder_f ServiceConditionChange_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceConditionChange_H_ */
#include <asn_internal.h>
