/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.txt"
 */

#ifndef	_UNIPDUCPOnlyFlag_H_
#define	_UNIPDUCPOnlyFlag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UNIPDUCPOnlyFlag */
typedef BOOLEAN_t	 UNIPDUCPOnlyFlag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UNIPDUCPOnlyFlag;
asn_struct_free_f UNIPDUCPOnlyFlag_free;
asn_struct_print_f UNIPDUCPOnlyFlag_print;
asn_constr_check_f UNIPDUCPOnlyFlag_constraint;
ber_type_decoder_f UNIPDUCPOnlyFlag_decode_ber;
der_type_encoder_f UNIPDUCPOnlyFlag_encode_der;
xer_type_decoder_f UNIPDUCPOnlyFlag_decode_xer;
xer_type_encoder_f UNIPDUCPOnlyFlag_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UNIPDUCPOnlyFlag_H_ */
#include <asn_internal.h>
