/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GgsnPgwR13Ber"
 * 	found in "./pgw-r13.asn"
 */

#ifndef	_URI_H_
#define	_URI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include "TimeStamp.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* URI */
typedef struct URI {
	long	*count	/* OPTIONAL */;
	IA5String_t	*uri	/* OPTIONAL */;
	long	*uriIdentifier	/* OPTIONAL */;
	long	*uriDataVolumeUplink	/* OPTIONAL */;
	long	*uriDataVolumeDownlink	/* OPTIONAL */;
	struct listOfUriTimeStamps {
		A_SEQUENCE_OF(TimeStamp_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfUriTimeStamps;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} URI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_URI;

#ifdef __cplusplus
}
#endif

#endif	/* _URI_H_ */
#include <asn_internal.h>
