/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_AFRecordInformation_H_
#define	_AFRecordInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AFChargingIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Flows;

/* AFRecordInformation */
typedef struct AFRecordInformation {
	AFChargingIdentifier_t	 aFChargingIdentifier;
	struct Flows	*flows	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AFRecordInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AFRecordInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Flows.h"

#endif	/* _AFRecordInformation_H_ */
#include <asn_internal.h>
