/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_ChangeOfCharCondition_H_
#define	_ChangeOfCharCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoSInformation.h"
#include "DataVolumeGPRS.h"
#include "ChangeCondition.h"
#include "TimeStamp.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EPCQoSInformation;

/* ChangeOfCharCondition */
typedef struct ChangeOfCharCondition {
	QoSInformation_t	*qosRequested	/* OPTIONAL */;
	QoSInformation_t	*qosNegotiated	/* OPTIONAL */;
	DataVolumeGPRS_t	*dataVolumeGPRSUplink	/* OPTIONAL */;
	DataVolumeGPRS_t	*dataVolumeGPRSDownlink	/* OPTIONAL */;
	ChangeCondition_t	 changeCondition;
	TimeStamp_t	 changeTime;
	OCTET_STRING_t	*userLocationInformation	/* OPTIONAL */;
	struct EPCQoSInformation	*ePCQoSInformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeOfCharCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeOfCharCondition;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EPCQoSInformation.h"

#endif	/* _ChangeOfCharCondition_H_ */
#include <asn_internal.h>
