/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_ChargingRuleBaseName_H_
#define	_ChargingRuleBaseName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChargingRuleBaseName */
typedef IA5String_t	 ChargingRuleBaseName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargingRuleBaseName;
asn_struct_free_f ChargingRuleBaseName_free;
asn_struct_print_f ChargingRuleBaseName_print;
asn_constr_check_f ChargingRuleBaseName_constraint;
ber_type_decoder_f ChargingRuleBaseName_decode_ber;
der_type_encoder_f ChargingRuleBaseName_encode_der;
xer_type_decoder_f ChargingRuleBaseName_decode_xer;
xer_type_encoder_f ChargingRuleBaseName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargingRuleBaseName_H_ */
#include <asn_internal.h>
