/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_CSGId_H_
#define	_CSGId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CSGId */
typedef OCTET_STRING_t	 CSGId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSGId;
asn_struct_free_f CSGId_free;
asn_struct_print_f CSGId_print;
asn_constr_check_f CSGId_constraint;
ber_type_decoder_f CSGId_decode_ber;
der_type_encoder_f CSGId_encode_der;
xer_type_decoder_f CSGId_decode_xer;
xer_type_encoder_f CSGId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CSGId_H_ */
#include <asn_internal.h>
