/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#include "Diagnostics.h"

static asn_TYPE_member_t asn_MBR_Diagnostics_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.gsm0408Cause),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsm0408Cause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.gsm0902MapErrorValue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsm0902MapErrorValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.itu_tQ767Cause),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"itu-tQ767Cause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.networkSpecificCause),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ManagementExtension,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkSpecificCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.manufacturerSpecificCause),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ManagementExtension,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"manufacturerSpecificCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.positionMethodFailureCause),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionMethodFailure_Diagnostic,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"positionMethodFailureCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.unauthorizedLCSClientCause),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UnauthorizedLCSClient_Diagnostic,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unauthorizedLCSClientCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Diagnostics, choice.diameterResultCodeAndExperimentalResult),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"diameterResultCodeAndExperimentalResult"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Diagnostics_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gsm0408Cause */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gsm0902MapErrorValue */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* itu-tQ767Cause */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* networkSpecificCause */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* manufacturerSpecificCause */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* positionMethodFailureCause */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* unauthorizedLCSClientCause */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* diameterResultCodeAndExperimentalResult */
};
static asn_CHOICE_specifics_t asn_SPC_Diagnostics_specs_1 = {
	sizeof(struct Diagnostics),
	offsetof(struct Diagnostics, _asn_ctx),
	offsetof(struct Diagnostics, present),
	sizeof(((struct Diagnostics *)0)->present),
	asn_MAP_Diagnostics_tag2el_1,
	8,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Diagnostics = {
	"Diagnostics",
	"Diagnostics",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Diagnostics_1,
	8,	/* Elements count */
	&asn_SPC_Diagnostics_specs_1	/* Additional specs */
};

