/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_EPCQoSInformation_H_
#define	_EPCQoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EPCQoSInformation */
typedef struct EPCQoSInformation {
	long	 qCI;
	long	*maxRequestedBandwithUL	/* OPTIONAL */;
	long	*maxRequestedBandwithDL	/* OPTIONAL */;
	long	*guaranteedBitrateUL	/* OPTIONAL */;
	long	*guaranteedBitrateDL	/* OPTIONAL */;
	long	*aRP	/* OPTIONAL */;
	long	*aPNAggregateMaxBitrateUL	/* OPTIONAL */;
	long	*aPNAggregateMaxBitrateDL	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EPCQoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EPCQoSInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _EPCQoSInformation_H_ */
#include <asn_internal.h>
