/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_FailureHandlingContinue_H_
#define	_FailureHandlingContinue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FailureHandlingContinue */
typedef BOOLEAN_t	 FailureHandlingContinue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FailureHandlingContinue;
asn_struct_free_f FailureHandlingContinue_free;
asn_struct_print_f FailureHandlingContinue_print;
asn_constr_check_f FailureHandlingContinue_constraint;
ber_type_decoder_f FailureHandlingContinue_decode_ber;
der_type_encoder_f FailureHandlingContinue_encode_der;
xer_type_decoder_f FailureHandlingContinue_decode_xer;
xer_type_encoder_f FailureHandlingContinue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FailureHandlingContinue_H_ */
#include <asn_internal.h>
