/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_MCC_MNC_H_
#define	_MCC_MNC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MCC-MNC */
typedef OCTET_STRING_t	 MCC_MNC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MCC_MNC;
asn_struct_free_f MCC_MNC_free;
asn_struct_print_f MCC_MNC_print;
asn_constr_check_f MCC_MNC_constraint;
ber_type_decoder_f MCC_MNC_decode_ber;
der_type_encoder_f MCC_MNC_encode_der;
xer_type_decoder_f MCC_MNC_decode_xer;
xer_type_encoder_f MCC_MNC_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MCC_MNC_H_ */
#include <asn_internal.h>
