/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_PDPAddress_H_
#define	_PDPAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IPAddress.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDPAddress_PR {
	PDPAddress_PR_NOTHING,	/* No components present */
	PDPAddress_PR_iPAddress
} PDPAddress_PR;

/* PDPAddress */
typedef struct PDPAddress {
	PDPAddress_PR present;
	union PDPAddress_u {
		IPAddress_t	 iPAddress;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDPAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDPAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _PDPAddress_H_ */
#include <asn_internal.h>
