/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_PGWRecord_H_
#define	_PGWRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RecordType.h"
#include "IMSI.h"
#include "GSNAddress.h"
#include "ChargingID.h"
#include "AccessPointNameNI.h"
#include "PDPType.h"
#include "DynamicAddressFlag.h"
#include "TimeStamp.h"
#include "CallDuration.h"
#include "CauseForRecClosing.h"
#include <NativeInteger.h>
#include "NodeID.h"
#include "LocalSequenceNumber.h"
#include "APNSelectionMode.h"
#include "MSISDN.h"
#include "ChargingCharacteristics.h"
#include "ChChSelectionMode.h"
#include <NULL.h>
#include <OCTET_STRING.h>
#include "PLMN-Id.h"
#include "IMEI.h"
#include "RATType.h"
#include "MSTimeZone.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "ServingNodeType.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum PGWRecord_PR {
	PGWRecord_PR_recordType,	/* Member recordType is present */
	PGWRecord_PR_servedIMSI,	/* Member servedIMSI is present */
	PGWRecord_PR_p_GWAddress,	/* Member p_GWAddress is present */
	PGWRecord_PR_chargingID,	/* Member chargingID is present */
	PGWRecord_PR_servingNodeAddress,	/* Member servingNodeAddress is present */
	PGWRecord_PR_accessPointNameNI,	/* Member accessPointNameNI is present */
	PGWRecord_PR_pdpPDNType,	/* Member pdpPDNType is present */
	PGWRecord_PR_servedPDPPDNAddress,	/* Member servedPDPPDNAddress is present */
	PGWRecord_PR_dynamicAddressFlag,	/* Member dynamicAddressFlag is present */
	PGWRecord_PR_recordOpeningTime,	/* Member recordOpeningTime is present */
	PGWRecord_PR_duration,	/* Member duration is present */
	PGWRecord_PR_causeForRecClosing,	/* Member causeForRecClosing is present */
	PGWRecord_PR_diagnostics,	/* Member diagnostics is present */
	PGWRecord_PR_recordSequenceNumber,	/* Member recordSequenceNumber is present */
	PGWRecord_PR_nodeID,	/* Member nodeID is present */
	PGWRecord_PR_recordExtensions,	/* Member recordExtensions is present */
	PGWRecord_PR_localSequenceNumber,	/* Member localSequenceNumber is present */
	PGWRecord_PR_apnSelectionMode,	/* Member apnSelectionMode is present */
	PGWRecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	PGWRecord_PR_chargingCharacteristics,	/* Member chargingCharacteristics is present */
	PGWRecord_PR_chChSelectionMode,	/* Member chChSelectionMode is present */
	PGWRecord_PR_iMSsignalingContext,	/* Member iMSsignalingContext is present */
	PGWRecord_PR_externalChargingID,	/* Member externalChargingID is present */
	PGWRecord_PR_servingNodePLMNIdentifier,	/* Member servingNodePLMNIdentifier is present */
	PGWRecord_PR_pSFurnishChargingInformation,	/* Member pSFurnishChargingInformation is present */
	PGWRecord_PR_servedIMEISV,	/* Member servedIMEISV is present */
	PGWRecord_PR_rATType,	/* Member rATType is present */
	PGWRecord_PR_mSTimeZone,	/* Member mSTimeZone is present */
	PGWRecord_PR_userLocationInformation,	/* Member userLocationInformation is present */
	PGWRecord_PR_cAMELChargingInformation,	/* Member cAMELChargingInformation is present */
	PGWRecord_PR_listOfServiceData,	/* Member listOfServiceData is present */
	PGWRecord_PR_servingNodeType,	/* Member servingNodeType is present */
	PGWRecord_PR_servedMNNAI,	/* Member servedMNNAI is present */
	PGWRecord_PR_p_GWPLMNIdentifier,	/* Member p_GWPLMNIdentifier is present */
	PGWRecord_PR_startTime,	/* Member startTime is present */
	PGWRecord_PR_stopTime,	/* Member stopTime is present */
	PGWRecord_PR_served3gpp2MEID,	/* Member served3gpp2MEID is present */
	PGWRecord_PR_pDNConnectionChargingID,	/* Member pDNConnectionChargingID is present */
	PGWRecord_PR_iMSIunauthenticatedFlag,	/* Member iMSIunauthenticatedFlag is present */
	PGWRecord_PR_userCSGInformation,	/* Member userCSGInformation is present */
	PGWRecord_PR_threeGPP2UserLocationInformation,	/* Member threeGPP2UserLocationInformation is present */
	PGWRecord_PR_servedPDPPDNAddressExt,	/* Member servedPDPPDNAddressExt is present */
	PGWRecord_PR_lowPriorityIndicator,	/* Member lowPriorityIndicator is present */
	PGWRecord_PR_dynamicAddressFlagExt,	/* Member dynamicAddressFlagExt is present */
	PGWRecord_PR_servingNodeiPv6Address,	/* Member servingNodeiPv6Address is present */
	PGWRecord_PR_p_GWiPv6AddressUsed,	/* Member p_GWiPv6AddressUsed is present */
	PGWRecord_PR_tWANUserLocationInformation,	/* Member tWANUserLocationInformation is present */
} PGWRecord_PR;

/* Forward declarations */
struct PDPAddress;
struct Diagnostics;
struct ManagementExtensions;
struct PSFurnishChargingInformation;
struct SubscriptionID;
struct UserCSGInformation;
struct IPAddress;
struct TWANUserLocationInfo;
struct ChangeOfServiceCondition;

/* PGWRecord */
typedef struct PGWRecord {
	RecordType_t	 recordType;
	IMSI_t	*servedIMSI	/* OPTIONAL */;
	GSNAddress_t	 p_GWAddress;
	ChargingID_t	 chargingID;
	struct servingNodeAddress {
		A_SEQUENCE_OF(struct IPAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} servingNodeAddress;
	AccessPointNameNI_t	*accessPointNameNI	/* OPTIONAL */;
	PDPType_t	*pdpPDNType	/* OPTIONAL */;
	struct PDPAddress	*servedPDPPDNAddress	/* OPTIONAL */;
	DynamicAddressFlag_t	*dynamicAddressFlag	/* OPTIONAL */;
	TimeStamp_t	 recordOpeningTime;
	CallDuration_t	 duration;
	CauseForRecClosing_t	 causeForRecClosing;
	struct Diagnostics	*diagnostics	/* OPTIONAL */;
	long	*recordSequenceNumber	/* OPTIONAL */;
	NodeID_t	*nodeID	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	LocalSequenceNumber_t	*localSequenceNumber	/* OPTIONAL */;
	APNSelectionMode_t	*apnSelectionMode	/* OPTIONAL */;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	ChargingCharacteristics_t	 chargingCharacteristics;
	ChChSelectionMode_t	*chChSelectionMode	/* OPTIONAL */;
	NULL_t	*iMSsignalingContext	/* OPTIONAL */;
	OCTET_STRING_t	*externalChargingID	/* OPTIONAL */;
	PLMN_Id_t	*servingNodePLMNIdentifier	/* OPTIONAL */;
	struct PSFurnishChargingInformation	*pSFurnishChargingInformation	/* OPTIONAL */;
	IMEI_t	*servedIMEISV	/* OPTIONAL */;
	RATType_t	*rATType	/* OPTIONAL */;
	MSTimeZone_t	*mSTimeZone	/* OPTIONAL */;
	OCTET_STRING_t	*userLocationInformation	/* OPTIONAL */;
	OCTET_STRING_t	*cAMELChargingInformation	/* OPTIONAL */;
	struct listOfServiceData {
		A_SEQUENCE_OF(struct ChangeOfServiceCondition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfServiceData;
	struct servingNodeType {
		A_SEQUENCE_OF(ServingNodeType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} servingNodeType;
	struct SubscriptionID	*servedMNNAI	/* OPTIONAL */;
	PLMN_Id_t	*p_GWPLMNIdentifier	/* OPTIONAL */;
	TimeStamp_t	*startTime	/* OPTIONAL */;
	TimeStamp_t	*stopTime	/* OPTIONAL */;
	OCTET_STRING_t	*served3gpp2MEID	/* OPTIONAL */;
	ChargingID_t	*pDNConnectionChargingID	/* OPTIONAL */;
	NULL_t	*iMSIunauthenticatedFlag	/* OPTIONAL */;
	struct UserCSGInformation	*userCSGInformation	/* OPTIONAL */;
	OCTET_STRING_t	*threeGPP2UserLocationInformation	/* OPTIONAL */;
	struct PDPAddress	*servedPDPPDNAddressExt	/* OPTIONAL */;
	NULL_t	*lowPriorityIndicator	/* OPTIONAL */;
	DynamicAddressFlag_t	*dynamicAddressFlagExt	/* OPTIONAL */;
	struct servingNodeiPv6Address {
		A_SEQUENCE_OF(struct IPAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *servingNodeiPv6Address;
	struct IPAddress	*p_GWiPv6AddressUsed	/* OPTIONAL */;
	struct TWANUserLocationInfo	*tWANUserLocationInformation	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pPGWRecord, PGWRecord_PR_x) */
	unsigned int _presence_map
		[((47+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PGWRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PGWRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDPAddress.h"
#include "Diagnostics.h"
#include "ManagementExtensions.h"
#include "PSFurnishChargingInformation.h"
#include "SubscriptionID.h"
#include "UserCSGInformation.h"
#include "GSNAddress.h"
#include "TWANUserLocationInfo.h"
#include "ChangeOfServiceCondition.h"

#endif	/* _PGWRecord_H_ */
#include <asn_internal.h>
