/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_RAIdentity_H_
#define	_RAIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RAIdentity */
typedef OCTET_STRING_t	 RAIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RAIdentity;
asn_struct_free_f RAIdentity_free;
asn_struct_print_f RAIdentity_print;
asn_constr_check_f RAIdentity_constraint;
ber_type_decoder_f RAIdentity_decode_ber;
der_type_encoder_f RAIdentity_encode_der;
xer_type_decoder_f RAIdentity_decode_xer;
xer_type_encoder_f RAIdentity_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RAIdentity_H_ */
#include <asn_internal.h>
