/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_RatingGroupId_H_
#define	_RatingGroupId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RatingGroupId */
typedef long	 RatingGroupId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RatingGroupId;
asn_struct_free_f RatingGroupId_free;
asn_struct_print_f RatingGroupId_print;
asn_constr_check_f RatingGroupId_constraint;
ber_type_decoder_f RatingGroupId_decode_ber;
der_type_encoder_f RatingGroupId_encode_der;
xer_type_decoder_f RatingGroupId_decode_xer;
xer_type_encoder_f RatingGroupId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RatingGroupId_H_ */
#include <asn_internal.h>
