/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_SGWChange_H_
#define	_SGWChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SGWChange */
typedef BOOLEAN_t	 SGWChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGWChange;
asn_struct_free_f SGWChange_free;
asn_struct_print_f SGWChange_print;
asn_constr_check_f SGWChange_constraint;
ber_type_decoder_f SGWChange_decode_ber;
der_type_encoder_f SGWChange_encode_der;
xer_type_decoder_f SGWChange_decode_xer;
xer_type_encoder_f SGWChange_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SGWChange_H_ */
#include <asn_internal.h>
