/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_SubscriptionIDType_H_
#define	_SubscriptionIDType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubscriptionIDType {
	SubscriptionIDType_eND_USER_E164	= 0,
	SubscriptionIDType_eND_USER_IMSI	= 1,
	SubscriptionIDType_eND_USER_SIP_URI	= 2,
	SubscriptionIDType_eND_USER_NAI	= 3,
	SubscriptionIDType_eND_USER_PRIVATE	= 4
} e_SubscriptionIDType;

/* SubscriptionIDType */
typedef long	 SubscriptionIDType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubscriptionIDType;
asn_struct_free_f SubscriptionIDType_free;
asn_struct_print_f SubscriptionIDType_print;
asn_constr_check_f SubscriptionIDType_constraint;
ber_type_decoder_f SubscriptionIDType_decode_ber;
der_type_encoder_f SubscriptionIDType_encode_der;
xer_type_decoder_f SubscriptionIDType_decode_xer;
xer_type_encoder_f SubscriptionIDType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriptionIDType_H_ */
#include <asn_internal.h>
