/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_TimeQuotaType_H_
#define	_TimeQuotaType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeQuotaType {
	TimeQuotaType_dISCRETETIMEPERIOD	= 0,
	TimeQuotaType_cONTINUOUSTIMEPERIOD	= 1
} e_TimeQuotaType;

/* TimeQuotaType */
typedef long	 TimeQuotaType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeQuotaType;
asn_struct_free_f TimeQuotaType_free;
asn_struct_print_f TimeQuotaType_print;
asn_constr_check_f TimeQuotaType_constraint;
ber_type_decoder_f TimeQuotaType_decode_ber;
der_type_encoder_f TimeQuotaType_encode_der;
xer_type_decoder_f TimeQuotaType_decode_xer;
xer_type_encoder_f TimeQuotaType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeQuotaType_H_ */
#include <asn_internal.h>
