/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#include "TWANUserLocationInfo.h"

static asn_TYPE_member_t asn_MBR_TWANUserLocationInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TWANUserLocationInfo, sSID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sSID"
		},
	{ ATF_POINTER, 1, offsetof(struct TWANUserLocationInfo, bSSID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bSSID"
		},
};
static ber_tlv_tag_t asn_DEF_TWANUserLocationInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TWANUserLocationInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sSID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* bSSID */
};
static asn_SEQUENCE_specifics_t asn_SPC_TWANUserLocationInfo_specs_1 = {
	sizeof(struct TWANUserLocationInfo),
	offsetof(struct TWANUserLocationInfo, _asn_ctx),
	asn_MAP_TWANUserLocationInfo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TWANUserLocationInfo = {
	"TWANUserLocationInfo",
	"TWANUserLocationInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TWANUserLocationInfo_tags_1,
	sizeof(asn_DEF_TWANUserLocationInfo_tags_1)
		/sizeof(asn_DEF_TWANUserLocationInfo_tags_1[0]), /* 1 */
	asn_DEF_TWANUserLocationInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TWANUserLocationInfo_tags_1)
		/sizeof(asn_DEF_TWANUserLocationInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TWANUserLocationInfo_1,
	2,	/* Elements count */
	&asn_SPC_TWANUserLocationInfo_specs_1	/* Additional specs */
};

