/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_UserCSGInformation_H_
#define	_UserCSGInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSGId.h"
#include "CSGAccessMode.h"
#include <NULL.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UserCSGInformation */
typedef struct UserCSGInformation {
	CSGId_t	 cSGId;
	CSGAccessMode_t	 cSGAccessMode;
	NULL_t	*cSGMembershipIndication	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserCSGInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserCSGInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _UserCSGInformation_H_ */
#include <asn_internal.h>
