/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_CallReferenceNumber_H_
#define	_CallReferenceNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallReferenceNumber */
typedef OCTET_STRING_t	 CallReferenceNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallReferenceNumber;
asn_struct_free_f CallReferenceNumber_free;
asn_struct_print_f CallReferenceNumber_print;
asn_constr_check_f CallReferenceNumber_constraint;
ber_type_decoder_f CallReferenceNumber_decode_ber;
der_type_encoder_f CallReferenceNumber_encode_der;
xer_type_decoder_f CallReferenceNumber_decode_xer;
xer_type_encoder_f CallReferenceNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallReferenceNumber_H_ */
#include <asn_internal.h>
