/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_ChangeOfMBMSCondition_H_
#define	_ChangeOfMBMSCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoSInformation.h"
#include "DataVolumeMBMS.h"
#include "ChangeCondition.h"
#include "TimeStamp.h"
#include "FailureHandlingContinue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeOfMBMSCondition */
typedef struct ChangeOfMBMSCondition {
	QoSInformation_t	*qosRequested	/* OPTIONAL */;
	QoSInformation_t	*qosNegotiated	/* OPTIONAL */;
	DataVolumeMBMS_t	*dataVolumeMBMSUplink	/* OPTIONAL */;
	DataVolumeMBMS_t	 dataVolumeMBMSDownlink;
	ChangeCondition_t	 changeCondition;
	TimeStamp_t	 changeTime;
	FailureHandlingContinue_t	*failureHandlingContinue	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeOfMBMSCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeOfMBMSCondition;

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeOfMBMSCondition_H_ */
#include <asn_internal.h>
