/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_IPBinaryAddress_H_
#define	_IPBinaryAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IPBinV4Address.h"
#include "IPBinV6AddressWithOrWithoutPrefixLength.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IPBinaryAddress_PR {
	IPBinaryAddress_PR_NOTHING,	/* No components present */
	IPBinaryAddress_PR_iPBinV4Address,
	IPBinaryAddress_PR_iPBinV6Address
} IPBinaryAddress_PR;

/* IPBinaryAddress */
typedef struct IPBinaryAddress {
	IPBinaryAddress_PR present;
	union IPBinaryAddress_u {
		IPBinV4Address_t	 iPBinV4Address;
		IPBinV6AddressWithOrWithoutPrefixLength_t	 iPBinV6Address;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPBinaryAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPBinaryAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _IPBinaryAddress_H_ */
#include <asn_internal.h>
