/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_IPBinV6AddressWithPrefixLength_H_
#define	_IPBinV6AddressWithPrefixLength_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IPBinV6Address.h"
#include "PDPAddressPrefixLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IPBinV6AddressWithPrefixLength */
typedef struct IPBinV6AddressWithPrefixLength {
	IPBinV6Address_t	 iPBinV6Address;
	PDPAddressPrefixLength_t	*pDPAddressPrefixLength	/* DEFAULT 64 */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPBinV6AddressWithPrefixLength_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPBinV6AddressWithPrefixLength;

#ifdef __cplusplus
}
#endif

#endif	/* _IPBinV6AddressWithPrefixLength_H_ */
#include <asn_internal.h>
