/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_ServiceIdentifier_H_
#define	_ServiceIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceIdentifier */
typedef unsigned long	 ServiceIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceIdentifier;
asn_struct_free_f ServiceIdentifier_free;
asn_struct_print_f ServiceIdentifier_print;
asn_constr_check_f ServiceIdentifier_constraint;
ber_type_decoder_f ServiceIdentifier_decode_ber;
der_type_encoder_f ServiceIdentifier_encode_der;
xer_type_decoder_f ServiceIdentifier_decode_xer;
xer_type_encoder_f ServiceIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceIdentifier_H_ */
#include <asn_internal.h>
