/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_SmsTpDestinationNumber_H_
#define	_SmsTpDestinationNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SmsTpDestinationNumber */
typedef OCTET_STRING_t	 SmsTpDestinationNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SmsTpDestinationNumber;
asn_struct_free_f SmsTpDestinationNumber_free;
asn_struct_print_f SmsTpDestinationNumber_print;
asn_constr_check_f SmsTpDestinationNumber_constraint;
ber_type_decoder_f SmsTpDestinationNumber_decode_ber;
der_type_encoder_f SmsTpDestinationNumber_encode_der;
xer_type_decoder_f SmsTpDestinationNumber_decode_xer;
xer_type_encoder_f SmsTpDestinationNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SmsTpDestinationNumber_H_ */
#include <asn_internal.h>
