/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#ifndef	_TWANUserLocationInfo_H_
#define	_TWANUserLocationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TWANUserLocationInfo */
typedef struct TWANUserLocationInfo {
	OCTET_STRING_t	 sSID;
	OCTET_STRING_t	*bSSID	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TWANUserLocationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TWANUserLocationInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _TWANUserLocationInfo_H_ */
#include <asn_internal.h>
