/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypes"
 * 	found in "./PGW_CDR_Format.asn"
 */

#include "UserCSGInformation.h"

static asn_TYPE_member_t asn_MBR_UserCSGInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UserCSGInformation, cSGId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSGId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cSGId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UserCSGInformation, cSGAccessMode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSGAccessMode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cSGAccessMode"
		},
	{ ATF_POINTER, 1, offsetof(struct UserCSGInformation, cSGMembershipIndication),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cSGMembershipIndication"
		},
};
static ber_tlv_tag_t asn_DEF_UserCSGInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_UserCSGInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cSGId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cSGAccessMode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* cSGMembershipIndication */
};
static asn_SEQUENCE_specifics_t asn_SPC_UserCSGInformation_specs_1 = {
	sizeof(struct UserCSGInformation),
	offsetof(struct UserCSGInformation, _asn_ctx),
	asn_MAP_UserCSGInformation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UserCSGInformation = {
	"UserCSGInformation",
	"UserCSGInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UserCSGInformation_tags_1,
	sizeof(asn_DEF_UserCSGInformation_tags_1)
		/sizeof(asn_DEF_UserCSGInformation_tags_1[0]), /* 1 */
	asn_DEF_UserCSGInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_UserCSGInformation_tags_1)
		/sizeof(asn_DEF_UserCSGInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UserCSGInformation_1,
	3,	/* Elements count */
	&asn_SPC_UserCSGInformation_specs_1	/* Additional specs */
};

